### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by DamonOehlman** [LightTable/Javascript#14] opened 2015-03-02 22:36 UTC
Not sure if this is just a problem I am having, but I've noticed that the rate at which I can effectively type in the latest version of the plugin is less than previous versions.  I went through a lot of different things when attempting to triage what the problem was here (clearing cache, turning off auto-completion, etc) but it wasn't until I completely removed the JS plugin that I was back to having what I would consider a nicely performing editor.

Just wondering if there is anything that has been added in the recent version that might contribute to this slow down in performance?

**Comment by cldwalker** [comment] 2015-03-06 16:24
The last possible commit that could have some perf impact was the Acorn upgrade. But that was months ago and I haven't noticed anything since then. Are you using any other plugins that effect js behavior? I've noticed LT-TernJS has caused perf impacts. Are you on OSX yosemite? There are known perf issues we are addressing for it.
Could you provide the .js file you're having trouble typing in? Without reproducible steps this can't be addressed.

**Comment by cldwalker** [comment] 2016-01-13 05:54
Closing due to lack of info

**Closed by cldwalker** 2016-01-13 05:54 UTC
